# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-15 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=64, verbose_name='\u4e8b\u4ef6\u540d\u79f0')),
                ('is_completed', models.SmallIntegerField(choices=[(0, '\u5b8c\u6210'), (1, '\u672a\u5b8c\u6210')], default=1, verbose_name='\u662f\u5426\u5b8c\u6210')),
                ('reason', models.CharField(blank=True, max_length=512, null=True, verbose_name='\u672a\u5b8c\u6210\u539f\u56e0')),
                ('completed_time', models.DateTimeField(blank=True, null=True, verbose_name='\u5b8c\u6210\u65f6\u95f4')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='\u603b\u7ed3')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='\u5907\u6ce8\u540d\u79f0')),
                ('detail', models.TextField(verbose_name='\u4e8b\u4ef6\u8be6\u7ec6')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128, verbose_name='token')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='\u90ae\u7bb1')),
                ('avatar', models.FileField(blank=True, null=True, upload_to='events/static/user/avatar', verbose_name='\u5934\u50cf')),
            ],
        ),
        migrations.AddField(
            model_name='token',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.UserInfo'),
        ),
        migrations.AddField(
            model_name='todo',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Type', verbose_name='\u4e8b\u4ef6\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.UserInfo', verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.UserInfo'),
        ),
    ]
