# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='events/static/user/avatar', verbose_name='\u5934\u50cf'),
        ),
    ]
