# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-15 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_completed',
            field=models.SmallIntegerField(choices=[(0, '\u5b8c\u6210'), (1, '\u672a\u5b8c\u6210')], default=1, verbose_name='\u662f\u5426\u5b8c\u6210'),
        ),
        migrations.AddField(
            model_name='todo',
            name='reason',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='\u672a\u5b8c\u6210\u539f\u56e0'),
        ),
        migrations.AddField(
            model_name='todo',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='\u603b\u7ed3'),
        ),
    ]
