# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190115_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
