# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-07 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181228_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='havetodo',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.UserInfo'),
        ),
    ]
