# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-09 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_havetodo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='havetodo',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.Type'),
        ),
    ]
