# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-14 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_history_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Type'),
        ),
    ]
