# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_havetodo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='havetodo',
            name='reason',
            field=models.CharField(default='\u61d2', max_length=512, verbose_name='\u672a\u5b8c\u6210\u539f\u56e0'),
        ),
    ]
