# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 10:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190110_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='havetodo',
            name='type',
        ),
        migrations.RemoveField(
            model_name='havetodo',
            name='user',
        ),
    ]
