# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-10 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190110_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='havetodo',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='\u603b\u7ed3'),
        ),
    ]
